global:
  domain: "enterprise.trdrhub.com"

gateway:
  enabled: true
  replicas: 2

nginx:
  enabled: true
  controller:
    enableCustomResources: true
    admissionWebhooks:
      enabled: true
    config:
      ssl-protocols: "TLSv1.2 TLSv1.3"
      ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
      client-body-buffer-size: "1m"
      client-body-timeout: "60s"
      client-header-buffer-size: "1k"
      large-client-header-buffers: "4 8k"
      enable-modsecurity: "true"
      enable-owasp-modsecurity-crs: "true"

    # mTLS Configuration
    extraArgs:
      - --default-ssl-certificate=trdrhub-system/enterprise-tls

    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:ACCOUNT:certificate/CERT-ID"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"

waf:
  enabled: true
  rules:
    - name: "rate-limit"
      rule: |
        location /api/ {
          limit_req zone=api burst=20 nodelay;
        }
    - name: "block-bad-bots"
      rule: |
        if ($http_user_agent ~* (curl|wget|python|postman)) {
          return 403;
        }

tenants:
  default:
    alias: "demo"
    mtls:
      enabled: false
    ipWhitelist: []

bankPilot:
  mtls:
    enabled: true
    clientCertSecret: "bank-client-certs"

  ipWhitelist:
    enabled: true
    defaultAction: "deny"

  tenants: []
  # Example tenant config:
  # - alias: "jpmorgan"
  #   domain: "jpmorgan.enterprise.trdrhub.com"
  #   sla: "platinum"
  #   mtls:
  #     clientCertSecret: "jpmorgan-client-certs"
  #   ipWhitelist:
  #     - "10.0.0.0/8"
  #     - "172.16.0.0/12"