import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  HelpCircle, 
  BookOpen, 
  MessageCircle, 
  Mail,
  ExternalLink,
  Play,
  FileText,
  AlertTriangle,
  CheckCircle2,
  ChevronDown
} from "lucide-react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "How does Price Verify determine market prices?",
    answer: "We aggregate data from multiple trusted sources including the World Bank Commodity Markets, Federal Reserve Economic Data (FRED), London Metal Exchange (LME), and major commodity exchanges. Prices are updated regularly and reflect current market conditions."
  },
  {
    question: "What variance percentage triggers a TBML flag?",
    answer: "By default, a price variance exceeding 50% from market value triggers a TBML (Trade-Based Money Laundering) flag. This threshold is based on FATF guidance and can be customized in Settings for your compliance requirements."
  },
  {
    question: "Which document formats are supported?",
    answer: "We support PDF, JPG, JPEG, and PNG formats. For best results, upload clear, high-resolution documents. Scanned documents are processed using AI-powered OCR (Optical Character Recognition)."
  },
  {
    question: "How accurate is the AI extraction?",
    answer: "Our AI extraction achieves 95%+ accuracy on standard commercial documents. We recommend reviewing extracted data before verification, especially for handwritten or low-quality documents."
  },
  {
    question: "What commodities are covered?",
    answer: "We cover 50+ major globally traded commodities across categories: Agriculture (cotton, rice, wheat, coffee), Energy (crude oil, natural gas), Metals (copper, aluminum, steel), and more. The database is continuously expanding."
  },
  {
    question: "Can I integrate Price Verify with my existing systems?",
    answer: "Yes! Professional and Business plans include API access for integration with your ERP, trade finance, or compliance systems. See our API documentation for details."
  },
  {
    question: "How should I handle TBML flags?",
    answer: "TBML flags indicate potential trade-based money laundering risk and require enhanced due diligence. Review the AI-generated risk narrative, request additional documentation from parties, and consult your compliance team. All flagged transactions should be documented in your SAR review process."
  },
  {
    question: "Are verification results admissible for compliance audits?",
    answer: "Yes. All verifications include timestamps, data sources, and audit trails. PDF reports generated by Price Verify are designed for regulatory compliance and can be included in your due diligence documentation."
  },
];

export default function HelpPage() {
  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Help & Documentation</h1>
        <p className="text-muted-foreground">
          Learn how to use Price Verify effectively.
        </p>
      </div>

      {/* Quick Start */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Play className="w-5 h-5" />
            Quick Start Guide
          </CardTitle>
          <CardDescription>Get started in 3 simple steps</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid sm:grid-cols-3 gap-6">
            <div className="text-center p-4">
              <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-3">
                <span className="text-xl font-bold text-primary">1</span>
              </div>
              <h3 className="font-medium mb-1">Upload Document</h3>
              <p className="text-sm text-muted-foreground">
                Upload an invoice, LC, or contract with commodity pricing
              </p>
            </div>
            <div className="text-center p-4">
              <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-3">
                <span className="text-xl font-bold text-primary">2</span>
              </div>
              <h3 className="font-medium mb-1">AI Extracts Prices</h3>
              <p className="text-sm text-muted-foreground">
                Our AI identifies commodities, quantities, and prices
              </p>
            </div>
            <div className="text-center p-4">
              <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-3">
                <span className="text-xl font-bold text-primary">3</span>
              </div>
              <h3 className="font-medium mb-1">Get Verification</h3>
              <p className="text-sm text-muted-foreground">
                Prices are verified against real-time market data
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Understanding Results */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            Understanding Your Results
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="flex items-start gap-4 p-4 rounded-lg bg-green-500/10 border border-green-500/20">
              <CheckCircle2 className="w-6 h-6 text-green-600 mt-0.5" />
              <div>
                <p className="font-medium text-green-600">PASS</p>
                <p className="text-sm">Price variance is within acceptable range (≤15%). No action required.</p>
              </div>
            </div>
            <div className="flex items-start gap-4 p-4 rounded-lg bg-yellow-500/10 border border-yellow-500/20">
              <AlertTriangle className="w-6 h-6 text-yellow-600 mt-0.5" />
              <div>
                <p className="font-medium text-yellow-600">WARNING</p>
                <p className="text-sm">Price variance is elevated (15-30%). Review recommended. May have legitimate explanations (quality premium, shipping costs, etc.)</p>
              </div>
            </div>
            <div className="flex items-start gap-4 p-4 rounded-lg bg-red-500/10 border border-red-500/20">
              <AlertTriangle className="w-6 h-6 text-red-600 mt-0.5" />
              <div>
                <p className="font-medium text-red-600">FAIL</p>
                <p className="text-sm">Price variance is significant (30-50%). Enhanced due diligence required. Request price justification documentation.</p>
              </div>
            </div>
            <div className="flex items-start gap-4 p-4 rounded-lg bg-purple-500/10 border border-purple-500/20">
              <Badge variant="destructive" className="mt-1">TBML</Badge>
              <div>
                <p className="font-medium text-purple-600">TBML FLAG</p>
                <p className="text-sm">Price variance exceeds 50%. Potential trade-based money laundering indicator. Follow your institution's SAR filing procedures.</p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* FAQs */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <HelpCircle className="w-5 h-5" />
            Frequently Asked Questions
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, idx) => (
              <AccordionItem key={idx} value={`faq-${idx}`}>
                <AccordionTrigger className="text-left">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </CardContent>
      </Card>

      {/* Resources */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BookOpen className="w-5 h-5" />
            Resources
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid sm:grid-cols-2 gap-4">
            <a href="#" className="flex items-center gap-3 p-4 rounded-lg border hover:bg-muted/50 transition-colors">
              <FileText className="w-5 h-5 text-muted-foreground" />
              <div className="flex-1">
                <p className="font-medium">API Documentation</p>
                <p className="text-sm text-muted-foreground">Integration guide for developers</p>
              </div>
              <ExternalLink className="w-4 h-4 text-muted-foreground" />
            </a>
            <a href="#" className="flex items-center gap-3 p-4 rounded-lg border hover:bg-muted/50 transition-colors">
              <BookOpen className="w-5 h-5 text-muted-foreground" />
              <div className="flex-1">
                <p className="font-medium">TBML Guide</p>
                <p className="text-sm text-muted-foreground">Understanding trade-based money laundering</p>
              </div>
              <ExternalLink className="w-4 h-4 text-muted-foreground" />
            </a>
            <a href="#" className="flex items-center gap-3 p-4 rounded-lg border hover:bg-muted/50 transition-colors">
              <FileText className="w-5 h-5 text-muted-foreground" />
              <div className="flex-1">
                <p className="font-medium">Commodity List</p>
                <p className="text-sm text-muted-foreground">Full list of supported commodities</p>
              </div>
              <ExternalLink className="w-4 h-4 text-muted-foreground" />
            </a>
            <a href="#" className="flex items-center gap-3 p-4 rounded-lg border hover:bg-muted/50 transition-colors">
              <Play className="w-5 h-5 text-muted-foreground" />
              <div className="flex-1">
                <p className="font-medium">Video Tutorials</p>
                <p className="text-sm text-muted-foreground">Step-by-step walkthroughs</p>
              </div>
              <ExternalLink className="w-4 h-4 text-muted-foreground" />
            </a>
          </div>
        </CardContent>
      </Card>

      {/* Contact Support */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <MessageCircle className="w-5 h-5" />
            Need More Help?
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col sm:flex-row gap-4">
            <Button variant="outline" className="flex-1">
              <MessageCircle className="w-4 h-4 mr-2" />
              Live Chat
            </Button>
            <Button variant="outline" className="flex-1">
              <Mail className="w-4 h-4 mr-2" />
              Email Support
            </Button>
          </div>
          <p className="text-sm text-muted-foreground text-center mt-4">
            Business hours: Monday - Friday, 9 AM - 6 PM (GMT)
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

